[package]
name = "medium-rust-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
tokio = { version = "1.40.0", features = ["full"] }
wtransport = "0.4.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
